on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      dotnet_version:
        required: false
        default: "8.0.x"
        type: string
      deploy_enabled:
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      - run: dotnet restore ./src
      - run: dotnet build ./src -c Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: dotnet test ./tests --no-build

  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.deploy_enabled == true }}
    steps:
      - run: echo "Deploying to ${{ inputs.environment }}"
