on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      dotnet_version:
        required: false
        default: "8.0.x"
        type: string
      deploy_enabled:
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      # Restaurar o projeto AuthService
      - run: dotnet restore ./Eventify.AuthService/Eventify.AuthService.csproj
      - run: dotnet build ./Eventify.AuthService/Eventify.AuthService.csproj -c Release --no-restore

      # Firebase secrets
      - name: Create Firebase Credential File
        run: |
          echo '${{ secrets.FIREBASE_CREDENTIAL_JSON }}' > $HOME/firebase-credentials.json
          echo "FIREBASE_CREDENTIAL_PATH=$HOME/firebase-credentials.json" >> $GITHUB_ENV
        shell: bash


  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: dotnet test ./Test --no-build

  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.deploy_enabled == true }}
    steps:
      - run: echo "Deploying AuthService to environment ${{ inputs.environment }}"